language: node_js
sudo: false

node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

install:
  - npm install -g codecov
  - npm run bootstrap

script:
  - npm run style
  - npm run coverage

after_success:
  - codecov
